name: Run build and tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  run_build_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        #uses: actions/checkout@v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up JDK 2
        #uses: actions/setup-java@v5
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        #uses: actions/cache@v5
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run (unit and integration) tests
        run: mvn verify